version: '3.8'

services:
  redis:
    image: redis:latest
    restart: unless-stopped

  frontend:
    image: frn
    ports:
      - 5000:5000

  backend:
    image: srv
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis