version: '3.8'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres

  frontend:
    image: frn
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: srv
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend
