version: '3.8'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db

  frontend:
    image: front
    build: ../example-frontend
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: server
    build: ../example-backend
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 80:80
    depends_on:
        - backend
        - frontend
    container_name: nginx